// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVH0rq1Pt3K09gP5SfdtN_rK61LAoqHU',
    appId: '1:997490989175:web:c82108d32fcc8519750e72',
    messagingSenderId: '997490989175',
    projectId: 'bukuku-e1104',
    authDomain: 'bukuku-e1104.firebaseapp.com',
    storageBucket: 'bukuku-e1104.firebasestorage.app',
    measurementId: 'G-2X7PNXTJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQieUiUBf9q8n0-Oa3hSOIKtiWT3c8g58',
    appId: '1:997490989175:android:494b38dc674d0921750e72',
    messagingSenderId: '997490989175',
    projectId: 'bukuku-e1104',
    storageBucket: 'bukuku-e1104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TBIU5JF_T4165Q_dymgFD0VbPl5Bnp8',
    appId: '1:997490989175:ios:2dc239b1235b19a7750e72',
    messagingSenderId: '997490989175',
    projectId: 'bukuku-e1104',
    storageBucket: 'bukuku-e1104.firebasestorage.app',
    iosBundleId: 'com.example.bukuku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9TBIU5JF_T4165Q_dymgFD0VbPl5Bnp8',
    appId: '1:997490989175:ios:2dc239b1235b19a7750e72',
    messagingSenderId: '997490989175',
    projectId: 'bukuku-e1104',
    storageBucket: 'bukuku-e1104.firebasestorage.app',
    iosBundleId: 'com.example.bukuku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsVH0rq1Pt3K09gP5SfdtN_rK61LAoqHU',
    appId: '1:997490989175:web:4165e560b664d2e8750e72',
    messagingSenderId: '997490989175',
    projectId: 'bukuku-e1104',
    authDomain: 'bukuku-e1104.firebaseapp.com',
    storageBucket: 'bukuku-e1104.firebasestorage.app',
    measurementId: 'G-W3LE0Q5SN6',
  );
}
